/**
 * Covey brand mark — a "covey" (small flock) of birds: an amber lead bird
 * with two slate birds behind it. This is the same mark used for the app
 * icon and Play listing (generated by scripts/android/lib/make-graphics.py);
 * keep the two in sync if the mark changes.
 */
export function CoveyMark({ size = 64, lead = '#f59e0b', flock = '#1e293b', class: cls }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      fill="none"
      class={cls}
      aria-hidden="true"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M35.4 45.9Q42.7 34.2 50 48.4Q57.3 34.2 64.6 45.9"
        stroke={lead}
        stroke-width="3.6"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M25.1 60.5Q29.8 52.9 34.4 62.2Q39.1 52.9 43.7 60.5"
        stroke={flock}
        stroke-width="2.9"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M56.3 60.5Q61 52.9 65.6 62.2Q70.3 52.9 74.9 60.5"
        stroke={flock}
        stroke-width="2.9"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>
  )
}
